import { Stack } from 'expo-router';
import React from 'react';
import { ScrollView, Text, View } from 'react-native';

export default function LegalScreen() {
    return (
        <>
            <Stack.Screen options={{ title: 'Legal', headerBackTitle: 'Back' }} />
            <ScrollView className="flex-1 bg-white p-6">
                <Text className="text-2xl font-bold text-slate-900 mb-6">Legal & Privacy</Text>

                <View className="mb-8">
                    <Text className="text-lg font-semibold text-slate-800 mb-3">Terms of Service</Text>
                    <Text className="text-slate-600 leading-6 mb-4">
                        By using Mobile Sous Chef, you agree to these terms. This application uses Artificial Intelligence (AI) to generate recipes and content.
                    </Text>
                    <Text className="text-slate-600 leading-6 mb-4">
                        1. <Text className="font-bold">AI Disclaimer:</Text> Recipes and images are generated by Google Gemini. While we strive for accuracy, AI can make mistakes. Always use your best judgment when cooking, especially regarding food safety and allergies.
                    </Text>
                    <Text className="text-slate-600 leading-6">
                        2. <Text className="font-bold">Usage:</Text> You are responsible for any content you generate or share. Do not use this app to generate harmful or illegal content.
                    </Text>
                </View>

                <View className="mb-8">
                    <Text className="text-lg font-semibold text-slate-800 mb-3">Privacy Policy</Text>
                    <Text className="text-slate-600 leading-6 mb-4">
                        We respect your privacy.
                    </Text>
                    <Text className="text-slate-600 leading-6 mb-4">
                        1. <Text className="font-bold">Data Collection:</Text> We do not collect personal data. Your recipes are stored locally on your device.
                    </Text>
                    <Text className="text-slate-600 leading-6">
                        2. <Text className="font-bold">Third Parties:</Text> When you generate a recipe, your prompt is sent to Google's Gemini API. Please review Google's privacy policy for how they handle API data.
                    </Text>
                </View>

                <View className="h-10" />
            </ScrollView>
        </>
    );
}
